### ISSUE TITLE
Query parameter matching not supporting on all platforms

### ISSUE THREAD

**Issue by dominickng** [wanderview/service-worker-scope-pattern-matching#5]
I'm a bit concerned about the proposed ability to match on query parameters. We will want this behaviour to be consistent in the web app manifest spec and for installed PWAs. However, platforms like Android do not offer the ability for apps to [differentiate captured URLs based on query parameters](https://developer.android.com/guide/components/intents-filters.html#DataTest). Specifically, Android supports capturing based on `<scheme>://<host>:<port>/<path>`, and thus we can't implement query scoping rules on Android natively.

The spec "legitimises" the ability to differentiate scopes based on query parameters. If sites start using this frequently, URL capturing won't work as expected on platforms that don't support this.

**Comment by mgiuca** [comment]
There are two parts to this: the difficulty of supporting link capturing for Manifest scopes on certain platforms (Android), and the question of "legitimization", regardless of platform, of whether we want to encourage sites to split their service workers by query parameter.

**Platform restrictions**

I guess it comes down to: do we either a) want the web matching capabilities to be constrained by the intersection of all platforms (i.e., if Android can't do it then we can't put it in the spec), or b) accept that some patterns won't be able to match on some platforms.

If we go with (a), then a further decision: do we a1) let the platform-specific constraints imposed on the Manifest matcher also constrain the SW scope syntax, for consistency, or a2) diverge the SW and Manifest scope matching syntax?

I would like them to be consistent, which means we need to decide how much we're willing to let individual platforms control our expressiveness.

**Legitimization**

Do we want sites to match based on query parameters (essentially making it possible to write sites that work offline but only when a certain query is matched)? I can see arguments for both ways here.

A pragmatic argument is that sites are already written with a server-side front-end forking off traffic to separate server applications based on query parameters. Convincing such a site to adopt service workers essentially requires the service worker to follow their internal structure. There's also the fact that it is possible to scope a SW based on a partial match on the query string today, albeit in a very brittle way (requiring the match to be the leftmost query parameter), so we would be removing that capability in the new syntax.

On the other hand, it creates a potentially poor user experience, where the user views it as a single application and are confused when parts of the application fail to respond when offline.

**Comment by wanderview** [comment]
Thanks for the feedback here.  We'll be sure to discuss this at the TPAC face-to-face meeting.

I did want to comment on one thing here, though:

> On the other hand, it creates a potentially poor user experience, where the user views it as a single application and are confused when parts of the application fail to respond when offline.

I disagree with this.  I don't think there is anything inherit in this feature that would lead to sites not being able to support offline.  If anything, the feedback I've gotten from one site is the lack of ability to align the service worker on query parameters has made it harder for them to fully support service workers and offline.

I think sites that separate their backend stack on query parameters have already crossed this bridge.  They in theory can get 500's/etc on one set of pages in their product and not others.  If the product team feels this is the best way to deliver their product, then I would expect them to support their features in that architecture.

Personally I don't think the service worker WG should be taking the position of telling sites how to structures their products and teams.  The WG lacks the context and constraints that individual product teams are working under.

**Comment by mgiuca** [comment]
I'm inclined to agree with that assessment (on the legitimization issue).

Note that neither @dominickng nor myself will be at TPAC. I look forward to hearing the outcome of these meetings.

**Comment by wanderview** [comment]
After thinking about this, I want to push back on the "legitimization" issue.

The argument here seems to assume that all use cases for service workers must necessarily map to valid use cases for manifest installation.  This doesn't seem right to me.  We encourage offline support for add-to-homescreen, so it makes sense to ensure that service workers support all manifest uses cases, but it doesn't follow that service workers must be limited to only manifest use cases.  Service workers can be used for lots of things where it would not make sense to have a manifest.

In particular, I don't think there is a use case for a manifest in the use case presented by the real site requesting to match on search parameters.  The site is a sub-component in a bigger product.  Any manifest and start URL would be associated with the overall product and not the sub-component.  Since this use case doesn't make sense for manifest, I'm not sure why the lack of manifest support should be blocking.

I understand there is a fear that more sites will begin using search parameters for top level products that want to be installed, but I find it highly unlikely.  There are other factors like user facing URL experience, server infrastructure, and best practice conventions which all discourage that approach.

Anyway, just my current thoughts.  Still very much an open topic and looking forward to getting more view points.

**Comment by dominickng** [comment]
@wanderview thanks for that. To clarify my legitimization point a bit, we could resolve this by explicitly calling out the limitation on the manifest spec side even as we try to keep as much compatibility with service worker as possible. I think though that we want to consider the value of keeping the implementations aligned against whether the additional use cases are important enough to cause divergence.

**Comment by mgiuca** [comment]
Thanks @wanderview --- I guess for both Dom and I our thinking is biased towards the manifest.

I don't think it would be a problem if we wanted to make an explicit divergence in the manifest by saying "you aren't allowed to include search parameter filtering" (in the manifest, even though you can for service workers). But I'd like for us to be clear on _why_ we're making that divergence.

I think this is a legitimate rationale: _"I don't think there is a use case for a manifest in the scenario presented by the real site requesting to match on search parameters. The site is a sub-component in a bigger product. Any manifest and start URL would be associated with the overall product and not the sub-component."_ (since it's a product-focused rationale, though we may also see cases where products _do_ want to distinguish themselves based on the query).

On the other hand, I don't think this is legitimate: _"Android doesn't let us filter on query string, so we don't allow it in the manifest."_ That's too much letting the lowest common denominator decide our capability set.

So we should decide whether the former rationale, applied _just_ to the manifest, is legitimate and sufficient to justify breaking consistency with the service worker pattern matching.

**Comment by wanderview** [comment]
One result from the TPAC face-to-face is that we are going to punt on search parameters support for now.  We probably have to support the legacy behavior in some way, but we would not be expanding that behavior for now.  (And maybe we can deprecate/remove the legacy search prefix matching support, but that would be a different effort.)

I'll leave this open until I update the explainer to remove the search parameters text.

**Comment by wanderview** [comment]
The explainer has been updated and no longer attempts to support arbitrary query parameter matching.  Closing.
